spring:
  application:
    name: numismatic-service
  profiles:
    active: profile1
  jackson:
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/numismatic_service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: numismatic_service
    password: numismatic_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB53Dialect
        current_session_context_class: thread
        hbm2ddl.auto: update
        format_sql: false
        show_sql: false
